### ISSUE TITLE
Fajny token bratku 😎😎😎

### ISSUE THREAD

**Issue by suchencjusz** [kacpereqo/piwobot#1]
fakturka na mailu @kacpereqo 

https://github.com/kacpereqo/piwobot/blame/5e596380bceaf5a61364f346118124509be1f52c/src/main.rs#L185C1-L185C1

**Comment by kacpereqo** [comment]
> fakturka na mailu @kacpereqo
> 
> https://github.com/kacpereqo/piwobot/blame/5e596380bceaf5a61364f346118124509be1f52c/src/main.rs#L185C1-L185C1

nieaktualne bratku b)
