### ISSUE TITLE
Brakuje seksu

### ISSUE THREAD

**Issue by Dromaeosaurs** [kacpereqo/piwobot#2]
Brakuje seksu (oraz nie szanuje was za granie w lol'a)
Oraz brakuje linka do odpowiedzi-szkola.pl

**Comment by Barabol** [comment]
+1

**Comment by Dromaeosaurs** [comment]
See? man

**Comment by piobed23** [comment]
Delta ujemna, brak rozwiązań

**Comment by Barabol** [comment]
Pierdolisz dawać sex

**Comment by kacpereqo** [comment]
@Barabol dodane

**Comment by Eghizio** [comment]
Elegancko 👍

**Comment by Dromaeosaurs** [comment]
Zajebiście
